# Generated by Django 5.1.2 on 2024-12-26 10:49

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('sign', models.ImageField(upload_to='media/')),
                ('thumb', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
